s10day12bbs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from bbs import views
from webqq import urls as chat_urls
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^chat/', include(chat_urls)),
    url(r'^$', views.index ),
    url(r'^life/$', views.life, name='life' ),
    url(r'^tech/$', views.tech, name='tech' ),
    url(r'^1024/$', views.category1024, name='category1024' ),
    url(r'^login/$', views.account_login, name='login'),
    url(r'^logout/$',views.account_logout,name='logout'),
    url(r'^article/(\d+)/$',views.article,name="article"),
    url(r'^article/create/$',views.create_article,name="create_article")

]

webqq/urls.py
from django.conf.urls import include, url
import views
urlpatterns = [
    url(r'^$',views.dashboard,name="chat"),
    url(r'^send_msg/$',views.send_msg,name="chat_send_msg"),
    url(r'^get_msg/$',views.get_msg,name="get_new_msg")


]

bbs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=254)
    category = models.ForeignKey('Category')
    content = models.TextField(max_length=100000)
    author = models.ForeignKey('UserProfile')
    summary = models.TextField(max_length=500)
    #thumb_ups = models.ForeignKey("ThumpUp",blank=True)
    #comments = models.ManyToManyField("Comment",blank=True)
    head_img = models.ImageField(upload_to="statics/imgs/upload")
    publish_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(unique=True,max_length=64)
    admins = models.ManyToManyField("UserProfile")
    def __unicode__(self):
        return self.name

class ThumpUp(models.Model):
    article = models.ForeignKey("Article")
    user = models.ForeignKey("UserProfile")
    date = models.DateTimeField(auto_now_add=True)
    def __unicode__(self):
        return self.article.title

class Comment(models.Model):
    article = models.ForeignKey("Article")
    user = models.ForeignKey("UserProfile")
    parent_comment = models.ForeignKey("Comment",blank=True,null=True,related_name='pid')
    comment = models.TextField(max_length=1024)
    date = models.DateTimeField(auto_now_add=True)
    def __unicode__(self):
        return self.comment

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=32)
    user_groups = models.ManyToManyField("UserGroup")
    friends = models.ManyToManyField('self',blank=True,related_name='my_friends')
    def __unicode__(self):
        return self.name

class UserGroup(models.Model):
    name = models.CharField(max_length=32,unique=True)
    def __unicode__(self):
        return self.name

webqq/models.py
from django.db import models
from bbs import models as bbs_models
# Create your models here.

class QQGroup(models.Model):
    name = models.CharField(max_length=64)
    founder = models.ForeignKey(bbs_models.UserProfile)
    brief = models.TextField(max_length=1024,default="nothing")
    admin = models.ManyToManyField(bbs_models.UserProfile,related_name="group_admins")
    members = models.ManyToManyField(bbs_models.UserProfile,related_name="group_members")
    member_limit = models.IntegerField(default=200)
    def __unicode__(self):
        return self.name

bbs/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
import models
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist
import  utils
import json
from django.contrib.auth import authenticate,login,logout

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.



def account_login(request):


    if request.method == 'GET':
        return  render(request,'login.html')

    else:
        print request.POST
        username = request.POST.get('username')
        passwd = request.POST.get('password')
        user = authenticate(username=username,password=passwd)
        if user is not None:
            login(request,user)
            #user.userprofile.online = True
            #user.userprofile.save()
            return  HttpResponseRedirect("/")
        else:
            return  render(request,'login.html',{
                'login_err': "Wrong username or password!"
            })

def account_logout(request):
    logout(request)
    return HttpResponseRedirect("/")

def index(request):
    article_list = models.Article.objects.all().order_by("-publish_date")
    paginator = Paginator(article_list, 3)  # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articles = paginator.page(paginator.num_pages)

    return render(request,'index.html',{
        'articles': articles
    })

def article(request,article_id):
    err_msg = ''
    try:
        article_obj = models.Article.objects.get(id=article_id)
        comments = utils.build_comments_tree(request)
    except ObjectDoesNotExist,e:
        err_msg = str(e)

    return render(request,"article.html",
                  {"article":article_obj,
                    "err_msg":err_msg,
                    "comments":comments},
                  )

def create_article(request):
    if request.method == "GET":
        return render(request,'create_article.html')
    elif request.method == "POST":
        print request.FILES
        bbs_generater = utils.ArticleGen(request)
        res = bbs_generater.create()
        html_ele = '''Your article <<a href="/article/%s">%s</a>> has been created successfully.
        ''' % (res.id,res.title)
        return HttpResponse(html_ele)
    else:
        pass

def life(request):

    return  render(request,'life.html')

def tech(request):

    return  render(request,'tech.html')
def category1024(request):

    return  render(request,'1024.html')

webqq/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
import json,datetime
# Create your views here.
import utils
import models
from django.core.exceptions import ObjectDoesNotExist

global_msg_dic = {}

def dashboard(request):
    return render(request,'webqq/dashboard.html')

def send_msg(request):

    print request.POST
    data =  request.POST.get("data")
    data = json.loads(data)
    data["date"] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    to_id = data.get("to_id")
    user_obj = models.bbs_models.UserProfile.objects.get(id=to_id)
    contact_type = data.get("contact_type")
    if contact_type == "single":
        if not global_msg_dic.has_key(to_id):
            global_msg_dic[to_id] = utils.Chat()
        global_msg_dic[to_id].msg_queue.put(data)
        print "\033[31;1mPush msg [%s] into user [%s] queue" % (data["msg"],user_obj)
    elif contact_type == "group":
        group_obj = models.QQGroup.objects.get(id = to_id)
        for member in group_obj.members.select_related():
            if member.id != request.user.userprofile.id:
                if not global_msg_dic.has_key(member.id):
                    global_msg_dic[member.id] = utils.Chat()
                global_msg_dic[member.id].msg_queue.put(data)
                print "\033[31;1mPush msg [%s] into user [%s] queue" % (data["msg"], member.name)
    return HttpResponse("dddddddddddddd")


def get_msg(request):
    uid = request.GET.get("uid")
   # new_msgs = []
    if uid:
    #     try:
    #         if not global_msg_dic.has_key(uid):
    #             global_msg_dic[uid] = utils.Chat()
    #         new_msgs = global_msg_dic[uid].get_msg(request)
    #     except ObjectDoesNotExist,e:
    #         print '\033[41;1m%s\033[0m' % str(e)
    # return HttpResponse(json.dumps(new_msgs))
        res = []
        if not global_msg_dic.has_key(uid):
            global_msg_dic[uid] = utils.Chat()
        res = global_msg_dic[uid].get_mmsg(request)
        return HttpResponse(json.dumps(res))
    else:
        return HttpResponse(json.dumps("uid not provided"))

templates/1024.html
{% extends 'index.html' %}


{% block content-left %}

    1024

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

templates/article.html
{% extends 'index.html' %}
{% load custom %}

{% block content-left %}

    <div class="blog-head">
        <h3>{{ article.title }}</h3>
        <div class="blog-summary-btn">
            <a>{{ article.author.name }}</a>
            <span>{{ article.publish_date }}</span>
            <span><i class="fa fa-comment" aria-hidden="true"></i>{{ article.comment_set.select_related.count }}</span>
            <span><i class="fa fa-star" aria-hidden="true"></i>{{ article.thumpup_set.select_related.count }}</span>

        </div>
        <div class="blog-content">
            {{ article.content|safe }}
        </div>
        <div class="comments-box">
            {% build_comment_tree comments %}

            <hr>

        </div>
    </div>


{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

templates/create_article.html
{% extends 'index.html' %}


{% block container %}


    <form class="form-horizontal" method="post" action="{% url "create_article" %}" enctype="multipart/form-data">{% csrf_token %}
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">文章标题</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="title" placeholder="title...">
    </div>
  </div>
    <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">文章简介</label>
    <div class="col-sm-10">
        <textarea class="form-control" rows="3" name="summary" placeholder="summary"></textarea>
    </div>
  </div>
    <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">标题图片</label>
    <div class="col-sm-10">
        <input type="file" name="head_img">
    </div>
  </div>
  <div class="form-group">
    <label for="content" class="col-sm-2 control-label">内容</label>
    <div class="col-sm-10">
      <textarea id="create_bbs" name="content"></textarea>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">发布</button>
    </div>
  </div>
</form>
{% endblock %}

{% block bottom-js %}
<script src="/static/plugins/tinymce/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">

    tinyMCE.init({
        selector:"#create_bbs",
        theme: "modern",
            //width: 300,
            height: 300,
            plugins: [
                 "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                 "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                 "save table contextmenu directionality emoticons template paste textcolor"
           ],
           //content_css: "css/content.css",
           toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons",
           style_formats: [
                {title: 'Bold text', inline: 'b'},
                {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
                {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
                {title: 'Example 1', inline: 'span', classes: 'example1'},
                {title: 'Example 2', inline: 'span', classes: 'example2'},
                {title: 'Table styles'},
                {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
            ]
    })
</script>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Post - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
    <!-- Custom CSS -->
    <link href="/static/css/blog-post.css" rel="stylesheet">
    <link href="/static/css/custom_v2.css" rel="stylesheet">
    <link href="/static/css/bootstrap.vertical-tabs.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block head-css %}
    {% endblock %}

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">XOXO</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul id="top_menu" class="nav navbar-nav">
                    <li>
                        <a href="/">全部</a>
                    </li>
                    <li>
                        <a href="{% url 'life' %}">生活</a>
                    </li>
                    <li>
                        <a href="{% url 'tech' %}">技术</a>
                    </li>
                    <li>
                        <a href="{% url 'category1024' %}">1024</a>
                    </li>
                    <li>
                        <a href="{% url 'chat' %}">聊天室</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'create_article' %}">发帖</a>
                        </li>
                    <li>

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user.userprofile.name }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/logout/">Logout</a></li>
                        </ul>

                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}">登录/注册</a>
                    </li>
                    {% endif %}

                </ul>

            </div>
            <!-- /.navbar-collapse -->

        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    {% block page-container %}
    <div class="container">
        {% block container %}
        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">
                {% block content-left %}

                {% for article in articles %}
                <div class="blog-box row">
                    <div class="head-img col-md-4">
                        <img src="/static/{{ article.head_img }}">
                    </div>
                    <div class="blog-summary-box col-md-8">
                        <h3><a href="{% url 'article' article.id %}">{{ article.title }}</a></h3>
                        <div class="blog-summary-btn">

                            <a>{{ article.author.name }}</a>
                            <span>{{ article.publish_date }}</span>

                            <span><i class="fa fa-star" aria-hidden="true"></i>4</span>
                            <span><i class="fa fa-comment" aria-hidden="true"></i>9</span>
                            <span><i class="fa fa-weixin" aria-hidden="true"></i></span>
                        </div>
                        <div class="blog-summary">
                            {{ article.summary }}
                        </div>
                    </div>
                </div>


                {% endfor %}

                <div class="pagination">
                    <span class="step-links">
                        {% if articles.has_previous %}
                            <a href="?page={{ articles.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ articles.number }} of {{ articles.paginator.num_pages }}.
                        </span>

                        {% if articles.has_next %}
                            <a href="?page={{ articles.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>

                <nav aria-label="...">
                    <ul class="pagination">
                        {% if articles.has_previous %}
                            <li><a href="?page={{ articles.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">上一页</span></a></li>
                        {% endif %}

                        {% for p_num in articles.paginator.page_range %}
                            {% if p_num == articles.number %}
                        <li class="active"><a href="?page={{ p_num }}">{{ p_num }}</a></li>
                            {% else %}
                        <li><a href="?page={{ p_num }}">{{ p_num }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if articles.has_next %}
                            <li><a href="?page={{ articles.next_page_number }}" aria-label="Next">下一页</a></li>
                        {% endif %}

                    </ul>
                </nav>

                {% endblock %}
            </div>


            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">
                {% block content-right %}
                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>
                {% endblock %}
            </div>

        </div>
        <!-- /.row -->

        <hr>
        {% endblock %}
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    {% endblock %}
    <!-- /.container -->

    <!-- jQuery -->
    <script src="/static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>
    {% block bottom-js %}
    <script type="text/javascript">


    </script>

    {% endblock %}
<script type="text/javascript">

    $(document).ready(function(){

        $("#top_menu a").each(function(){

            if ($(this).attr("href") == "{{ request.path }}"){
                $(this).parent().addClass("active");
            };
        });//end each

        /*

        */






    });// end doc ready

</script>

</body>

</html>

templates/life.html
{% extends 'index.html' %}


{% block content-left %}

    生活页

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

templates/login.html
{% extends 'index.html' %}

{% block container %}
<div>
    <form method="post" action="{% url 'login' %}">{% csrf_token %}

        <input type="text" name="username" placeholder="username" />
        <input type="password" name="password" placeholder="password" />
        <input type="submit" value="Login" class="btn btn-success" />

    </form>

    <p style="color: red">{{ login_err }}</p>
</div>

{% endblock %}

templates/logout.html
{% extends 'index.html' %}

{% block container %}
<div>
    <form method="post" action="{% url 'login' %}">{% csrf_token %}

        <input type="text" name="username" placeholder="username" />
        <input type="password" name="password" placeholder="password" />
        <input type="submit" value="Login" class="btn btn-success" />

    </form>

    <p style="color: red">{{ login_err }}</p>
</div>

{% endblock %}

templates/tech.html
{% extends 'index.html' %}


{% block content-left %}

    technique

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}